spring:
  profiles:
    default: test
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
  flyway:
    enabled: false  # Disable Flyway for tests
  retry:
    max-attempts: 1  # Only one attempt for testing purposes
    initial-interval: 1000
    multiplier: 2
    max-interval: 30000
