spring:
  profiles:
    default: test
  jpa:
    open-in-view: false
  datasource: # Use an in-memory H2 database for tests
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    platform: h2
  flyway:
    enabled: false  # Disable Flyway for tests
  rabbitmq:
    queues:
      users-queue: q.users  # Test queue
