spring:
  profiles:
    default: test
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
  flyway:
    enabled: false  # Disable Flyway for tests
  retry:
    max-attempts: 1  # Only one attempt for testing purposes
    initial-interval: 1000
    multiplier: 2
    max-interval: 30000
security:
  jwt:
    secret-key: TH1S_1S_@_S3CR3T_K3Y_4_1NT3GRAT10N_3NVS
  enabled: false
