server:
  port: 8081

spring:
  application:
    name: user-command-service
  datasource:
    url: jdbc:mysql://localhost:3306/user-db
    username: user-db
    password: user-db
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: true
