spring:
  datasource:
    url: jdbc:sqlite:file:users.db?cache=shared
    hikari:
      connectionTimeout: 1000
  jpa:
    open-in-view: false
    show-sql: true
  flyway:
    enabled: true
  retry:
    max-attempts: 4
    initial-interval: 1000
    multiplier: 2
    max-interval: 30000
