server:
  port: 8081

spring:
  application:
    name: user-command-service
  datasource:
    url: jdbc:mysql://localhost:3306/user-db
    username: user-db
    password: user-db
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  flyway:
    enabled: true
  retry:
    max-attempts: 4
    initial-interval: 1000
    multiplier: 2
    max-interval: 30000
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    queues:
      users-queue: q.users
