server:
  port: 8082

spring:
  application:
    name: user-query-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: user-mongodb
      uuid-representation: standard
