server:
  port: 8082

spring:
  application:
    name: user-query-service
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=user-db;encrypt=true;trustServerCertificate=true;
    username: sa
    password: Str#ng_Passw#rd
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      connectionTimeout: 5000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
